services:
  config-server:
    image: bookings-service/config-service:latest
    env_file:
      - .env
    environment:
      VAULT_HOST: vault
      SERVER_PORT: "8071"
    ports:
      - "8071:8071"
    depends_on:
      vault:
        condition: service_healthy
      vault-configure:
        condition: service_completed_successfully
    networks:
      backend:
        aliases:
          - "config-server"
  aircraft-service:
    image: bookings-service/aircraft-service:latest
    environment:
      SERVER_PORT: "8083"
      CONFIG_SERVER: "http://config-server:8071"
      DATABASE_SERVER: "database:5432/demo"
      EUREKA_SERVER: "http://eureka-server:8070/eureka/"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
      vault:
        condition: service_healthy
    ports:
      - "8083:8083"
    networks:
      - backend
  airport-service:
    image: bookings-service/airport-service:latest
    environment:
      CONFIG_SERVER: "http://config-server:8071"
      SERVER_PORT: "8081"
      DATABASE_SERVER: "database:5432/demo"
      EUREKA_SERVER: "http://eureka-server:8070/eureka/"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
      vault:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend
  flight-service:
    image: bookings-service/flight-service:latest
    environment:
      CONFIG_SERVER: "http://config-server:8071"
      SERVER_PORT: "8082"
      DATABASE_SERVER: "database:5432/demo"
      EUREKA_SERVER: "http://eureka-server:8070/eureka/"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
      vault:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - backend
  database:
    image: postgres:16.2
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ${DATABASE_VOLUME_PATH}:/var/lib/postgresql/data
      - ./buildSrc/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  vault:
    image: hashicorp/vault:latest
    restart: always
    entrypoint: vault server -dev -dev-listen-address=0.0.0.0:8200
    env_file:
      - .env
    environment:
      VAULT_ADDR: http://vault:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ${VAULT_VOLUME_PATH}:/vault/file
    healthcheck:
      test: [ "CMD", "vault", "status" ]
    networks:
      backend:
        aliases:
          - "vault"
  vault-configure:
    image: hashicorp/vault:latest
    volumes:
      - ./buildSrc/src/main/resources/vault.sh:/scripts/vault.sh
    command: sh /scripts/vault.sh
    env_file:
      - .env
    environment:
      VAULT_ADDR: http://vault:8200
    cap_add:
      - IPC_LOCK
    depends_on:
      vault:
        condition: service_healthy
    networks:
      - backend
  eureka-server:
    image: bookings-service/eureka-service:latest
    environment:
      CONFIG_SERVER: "http://config-server:8071"
      EUREKA_HOST: "eureka-server"
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eureka-server"
  gateway-server:
    image: bookings-service/gateway-service:latest
    environment:
      CONFIG_SERVER: "http://config-server:8071"
      EUREKA_SERVER: "http://eureka-server:8070/eureka/"
      SERVER_PORT: "8072"
    ports:
      - "8072:8072"
    depends_on:
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway-server"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ${KEYCLOAK_VOLUME_PATH}:/opt/keycloak/data/
      - ${KEYCLOAK_VOLUME_PATH}/import:/opt/keycloak/data/import
    networks:
      backend:
        aliases:
          - "keycloak"
  redis:
    image: redis:alpine3.20
    ports:
      - "6379:6379"
    networks:
      backend:
        aliases:
          - "redis"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      backend:
        aliases:
          - "zookeeper"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      backend:
        aliases:
          - "kafka-server"
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
       KAFKA_CLUSTERS_0_NAME: local
       KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
       KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
       DYNAMIC_CONFIG_ENABLED: 'true'
    links:
      - kafka
      - zookeeper
    networks:
      backend:
        aliases:
          - "kafka-ui"
networks:
  backend:
    driver: bridge