services:
  configserver:
    image: bookings-service/config-service:latest
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
  aircraft-service:
    image: bookings-service/aircraft-service:latest
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SERVER_PORT: "8080"
      SPRING_DATASOURCE_URL: " jdbc:postgresql://database:5432/demo"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend
  airport-service:
    image: bookings-service/airport-service:latest
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SERVER_PORT: "8081"
      SPRING_DATASOURCE_URL: " jdbc:postgresql://database:5432/demo"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend
  database:
    image: postgres:16.2
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       ${DB_NAME}
    volumes:
      - ${VOLUME_PATH}:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge